tools/coreutils: update to 9.9
Release Notes:
https://lists.gnu.org/archive/html/info-gnu/2025-11/msg00000.html

Manually refresh patch:
- 000-bootstrap.patch

Add `TARGET_CFLAGS += -std=gnu17` to fix error in the form:
  src/df.c: In function 'decode_output_arg':
  src/df.c:444:29: error: unknown type name 'typeof'
   444 |       for (idx_t i = 0; i < countof (field_data); i++)
       |                               ^~~~~~~

Signed-off-by: Nick Hainke <vincent@systemli.org>